# ===================================================================
# Arquivo de Configuração do Streamlit para o "Programa +GEMS"
# TEMA CLARO
# ===================================================================

[theme]
# A MUDANÇA MAIS IMPORTANTE: Define o tema base como "claro".
base = "light"

# Cor principal usada para botões, seletores, e outros widgets.
# Um azul vibrante e profissional que funciona bem em fundos claros.
primaryColor = "#0068C9"

# Cor de fundo principal do aplicativo.
# Um cinza muito claro para ser mais suave aos olhos que o branco puro.
backgroundColor = "#F0F2F6"

# Cor de fundo para a barra lateral, expanders, e outros elementos secundários.
# Branco puro para criar um contraste limpo com o fundo principal.
secondaryBackgroundColor = "#FFFFFF"

# Cor do texto principal.
# Um cinza escuro para ótima legibilidade, menos agressivo que o preto puro.
textColor = "#31333F"

# Família da fonte. "sans serif" é uma escolha moderna e limpa.
font = "sans serif"


[server]
# Desativa a coleta de estatísticas de uso anônimas pelo Streamlit.
gatherUsageStats = false
# Permite que o servidor rode em modo "headless".
headless = true


[client]
# Garante que a barra de navegação com as páginas seja sempre visível.
showSidebarNavigation = true